
Parameter-settings: 

max-tries 10
max-tours 100
optimum 1
time 10.000000
num-ants 25
num-neigh 20
alpha 1.000000
beta 2.000000
rho 0.500000
q_0 0.000000
branch-up 1.000010
ls_flag 3
nn_ls 20
dlb_flag 1
as_flag 0
eas_flag 0
ras_flag 0
mmas_flag 1
bwas_flag 0
acs_flag 0

Best: 72	 Iterations:      1	 B-Fac 0.00000	 Time 0.00	 Tot.time 10.00
Best: 72	 Iterations:      1	 B-Fac 0.00000	 Time 0.00	 Tot.time 10.00
Best: 72	 Iterations:      1	 B-Fac 0.00000	 Time 0.00	 Tot.time 10.00
Best: 72	 Iterations:      1	 B-Fac 0.00000	 Time 0.00	 Tot.time 10.00
Best: 72	 Iterations:      1	 B-Fac 0.00000	 Time 0.00	 Tot.time 10.00
Best: 72	 Iterations:      1	 B-Fac 0.00000	 Time 0.00	 Tot.time 10.00
Best: 72	 Iterations:      1	 B-Fac 0.00000	 Time 0.00	 Tot.time 10.00
Best: 72	 Iterations:      1	 B-Fac 0.00000	 Time 0.00	 Tot.time 10.00
Best: 72	 Iterations:      1	 B-Fac 0.00000	 Time 0.00	 Tot.time 10.00
Best: 72	 Iterations:      1	 B-Fac 0.00000	 Time 0.00	 Tot.time 10.00

Average-Best: 72.00	 Average-Iterations: 1.00
Stddev-Best: 0.00 	 Stddev Iterations: 0.00
Best try: 72		 Worst try: 72

Avg.time-best: 0.00 stddev.time-best: 0.00

Avg.time-total: 10.00 stddev.time-total: 0.00
 excess best = 71.000000, excess average = 71.000000, excess worst = 71.000000
