
ACO algorithms for the TSP, v1.0

Parameter-settings: 

max-tries 10
max-tours 100
optimum 1
time 10.000000
num-ants 25
num-neigh 20
alpha 1.000000
beta 2.000000
rho 0.500000
q_0 0.000000
branch-up 1.000010
ls_flag 3
nn_ls 20
dlb_flag 1
as_flag 0
eas_flag 0
ras_flag 0
mmas_flag 1
bwas_flag 0
acs_flag 0

begin problem ../Dados TSP/facil_ulysses22_TSPLIB.tsp
seed 1225574544
begin try 0 
best 72	 iteration 1	 tours 27	 time 0.000
end try 0

seed 510793091
begin try 1 
best 72	 iteration 1	 tours 27	 time 0.000
end try 1

seed 2031236127
begin try 2 
best 72	 iteration 1	 tours 27	 time 0.000
end try 2

seed 1390643797
begin try 3 
best 72	 iteration 1	 tours 27	 time 0.000
end try 3

seed 1638573235
begin try 4 
best 72	 iteration 1	 tours 27	 time 0.000
end try 4

seed 764534329
begin try 5 
best 72	 iteration 1	 tours 27	 time 0.000
end try 5

seed 1743234182
begin try 6 
best 72	 iteration 1	 tours 27	 time 0.000
end try 6

seed 1228930674
begin try 7 
best 72	 iteration 1	 tours 27	 time 0.000
end try 7

seed 1550306361
begin try 8 
best 72	 iteration 1	 tours 27	 time 0.000
end try 8

seed 78910998
begin try 9 
best 72	 iteration 1	 tours 27	 time 0.000
end try 9

end problem ulysses22.tsp
