/*
 * FrameGA.java
 *
 * Created on 7 de Outubro de 2008, 17:39
 */

package visao;

import java.io.File;

import javax.swing.JFileChooser;

import org.jgap.IChromosome;

import buscaLocal.BuscaLocalCruzamento;

import controle.GA.TSP;
import controle.arquivo.FileManager;

/**
 *
 * @author  thiago
 */
public class FrameGA extends javax.swing.JFrame {
    
    private File selectedFile;
	/** Creates new form FrameGA */
    public FrameGA() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    //11448.288374900818
    private void initComponents() {

        jTextFieldPopulacao = new javax.swing.JTextField();
        jLabelPopulacao = new javax.swing.JLabel();
        jLabelGeracoes = new javax.swing.JLabel();
        jTextFieldGeracoes = new javax.swing.JTextField();
        jLabelPasso = new javax.swing.JLabel();
        jTextFieldPasso = new javax.swing.JTextField();
        jTextFieldArquivo = new javax.swing.JTextField();
        jButtonArquivo = new javax.swing.JButton();
        jButtonIniciar = new javax.swing.JButton();
        jLabelSelecao = new javax.swing.JLabel();
        jComboBoxSelecao = new javax.swing.JComboBox();
        jCheckBoxBuscaLocal = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

		jTextFieldPopulacao.setText("250"); // NOI18N
		jTextFieldPopulacao.setName("jTextFieldPopulacao"); // NOI18N

		jLabelPopulacao.setText("Populacao"); // NOI18N
		jLabelPopulacao.setName("jLabelPopulacao"); // NOI18N

		jLabelGeracoes.setText("geracoes"); // NOI18N
		jLabelGeracoes.setName("jLabelGeracoes"); // NOI18N

		jTextFieldGeracoes.setText("100"); // NOI18N
		jTextFieldGeracoes.setName("jTextFieldGeracoes"); // NOI18N

		jLabelPasso.setText("Passo"); // NOI18N
		jLabelPasso.setName("jLabelPasso"); // NOI18N

		jTextFieldPasso.setText("50"); // NOI18N
		jTextFieldPasso.setName("jTextFieldPasso"); // NOI18N

		jTextFieldArquivo.setText("Selecione o Arquivo"); // NOI18N
		jTextFieldArquivo.setName("jTextFieldArquivo"); // NOI18N

		jButtonArquivo.setText("..."); // NOI18N
		jButtonArquivo.setName("jButtonArquivo"); // NOI18N
		jButtonArquivo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonArquivoActionPerformed(evt);
			}
		});

		jButtonIniciar.setText("Iniciar"); // NOI18N
		jButtonIniciar.setName("jButtonIniciar"); // NOI18N
		jButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonIniciarActionPerformed(evt);
			}
		});

		jLabelSelecao.setText("Selecao"); // NOI18N
		jLabelSelecao.setName("jLabelSelecao"); // NOI18N

		jComboBoxSelecao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tournament", "Roulette" }));
		jComboBoxSelecao.setName("jComboBoxSelecao"); // NOI18N
		
		jCheckBoxBuscaLocal.setText("Busca Local?"); // NOI18N
        jCheckBoxBuscaLocal.setName("jCheckBoxBuscaLocal"); // NOI18N
        jCheckBoxBuscaLocal.setSelected(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelSelecao))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPopulacao)
                            .addComponent(jLabelGeracoes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxSelecao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldGeracoes)
                                    .addComponent(jTextFieldPopulacao, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabelPasso)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldPasso, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCheckBoxBuscaLocal))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextFieldArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonArquivo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(233, Short.MAX_VALUE)
                        .addComponent(jButtonIniciar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPopulacao)
                    .addComponent(jTextFieldPopulacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGeracoes)
                    .addComponent(jTextFieldGeracoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPasso)
                    .addComponent(jTextFieldPasso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSelecao)
                    .addComponent(jComboBoxSelecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxBuscaLocal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonArquivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonIniciar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

	private void jButtonArquivoActionPerformed(java.awt.event.ActionEvent evt) {
		JFileChooser filec=new JFileChooser();
        filec.showDialog(this, "Carregar");
        this.selectedFile=filec.getSelectedFile();
        this.jTextFieldArquivo.setText(filec.getSelectedFile().getAbsolutePath());
	}

	private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			float[][] dados=FileManager.carregaDados(this.selectedFile);							

			TSP t = new TSP(dados,this.jComboBoxSelecao.getSelectedIndex(),this.jCheckBoxBuscaLocal.isSelected());		      		     


			IChromosome bestSolutionSoFar = t.getPopulacao().getFittestChromosome();
			//System.out.println(bestSolutionSoFar);
			System.out.println("Score " +
					(Integer.MAX_VALUE / 2 - bestSolutionSoFar.getFitnessValue()));

			FrameGrafico ini=new FrameGrafico("Best I: 0 iterações",bestSolutionSoFar);
			ini.Show();

			int iteracoes=0;
			int passo= Integer.parseInt(jTextFieldPasso.getText());
			int max= Integer.parseInt(this.jTextFieldGeracoes.getText());

			BuscaLocalCruzamento busca=new BuscaLocalCruzamento();
			while(iteracoes < max){
				if( (iteracoes+passo) >max){
					passo=max-passo;
				}

				t.evoluir(passo);
				iteracoes+=passo;

				bestSolutionSoFar = t.getPopulacao().getFittestChromosome();				
				//System.out.println("teste->"+bestSolutionSoFar.getFitnessValueDirectly());			      
				System.out.println("Score " +
						(Integer.MAX_VALUE / 2 - bestSolutionSoFar.getFitnessValue()));

				FrameGrafico end=new FrameGrafico("Best I: "+ iteracoes +" iterações",bestSolutionSoFar);
				end.Show();
			}		     
			
			busca.operate(bestSolutionSoFar,false);
			System.out.println("Score " +
					(Integer.MAX_VALUE / 2 - bestSolutionSoFar.getFitnessValue()));
			busca.operate(bestSolutionSoFar,false);
			System.out.println("Score " +
					(Integer.MAX_VALUE / 2 - bestSolutionSoFar.getFitnessValue()));
			busca.operate(bestSolutionSoFar,false);
			System.out.println("Score " +
					(Integer.MAX_VALUE / 2 - bestSolutionSoFar.getFitnessValue()));
			
			FrameGrafico end=new FrameGrafico("Best I: "+ iteracoes +" iterações",bestSolutionSoFar);
			end.Show();

			jButtonIniciar.setEnabled(false);
			//FileManager.saveStrategyState(t.getPopulacao(),"/home/thiago/teste.ga");
		}
		catch (Exception ex) {
			ex.printStackTrace();
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new FrameGA().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify
    private javax.swing.JButton jButtonArquivo;
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JCheckBox jCheckBoxBuscaLocal;
    private javax.swing.JComboBox jComboBoxSelecao;
    private javax.swing.JLabel jLabelGeracoes;
    private javax.swing.JLabel jLabelPasso;
    private javax.swing.JLabel jLabelPopulacao;
    private javax.swing.JLabel jLabelSelecao;
    private javax.swing.JTextField jTextFieldArquivo;
    private javax.swing.JTextField jTextFieldGeracoes;
    private javax.swing.JTextField jTextFieldPasso;
    private javax.swing.JTextField jTextFieldPopulacao;
    // End of variables declaration

}
